name: "export"
on:
  push:
    tags:
      - v*

env:
  GODOT_VERSION: 3.4.4

jobs:
  export-web:
    name: web export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.4.4
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install tox
        run: python -m pip install tox --user
      - name: build
        run: python -m tox -e build
      - name: upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: web
          path: build/web
      - name: install rsync
        run: |
          apt-get update && apt-get install -y rsync
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/web
